### PR TITLE
add nop 4.20 plugin

### PR DESCRIPTION
**Pull request by Lukejkw**

### CODE REVIEW

**Review by quarties — CHANGES_REQUESTED** [review]
Hi @Lukejkw! Thanks for this PR :-) Could you also add dist for `nop42`? Then I'll review if everything works fine :-)

**Review by quarties — CHANGES_REQUESTED** [review]
1. It looks like the whole [`obj` folder](https://github.com/Lukejkw/integration-nopcommerce/tree/add/nop42/src/nop42/Nop.Plugin.Widgets.LiveChatInc/obj) is redundant. If that's true, please remove it from the repository.
2. Please rename dist file to match other dists: `LiveChat-nopCommerce-4-2.zip`.
3. I tried to install plugin from zip package that you had provided, but unfortunately I wasn't able to. I received the following error: `The archive should contain only one root plugin or theme directory. For example, Payments.PayPalDirect or DefaultClean. To upload multiple items, the archive should have the 'uploadedItems.json' file in the root`
This might be an issue with my dev env. Could you confirm that installation via zip package upload works?

**Comment by Lukejkw** [comment]
I will try and get to these fixes as soon as I can.

**Comment by quarties** [comment]
Closing due to no response.

**Pull request closed without merging**
